const {chromium}=require('/opt/node22/lib/node_modules/playwright');
const B='http://localhost:8082';let F=0;const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)F++;};
const q=(s)=>require('child_process').execSync("php -r \"require '/tmp/wpt2/wp-load.php'; global \\$wpdb; "+s+"\"").toString().trim();
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});const pg=await (await b.newContext({viewport:{width:1300,height:900}})).newPage();const errs=[];pg.on('response',async r=>{if(/upload/.test(r.url()))console.log('R',r.status(),r.url().slice(-20),(await r.text()).slice(0,200))});pg.on('pageerror',e=>errs.push(e.message));pg.on('dialog',d=>d.accept());
await pg.goto(B+'/entrar/');await pg.fill('input[name=email]','admin');await pg.fill('input[name=senha]','SENHA_DO_ADMIN_DE_TESTE');await Promise.all([pg.waitForNavigation(),pg.click('button[type=submit]')]);
await pg.goto(B+'/painel/novo-pedido/');
await pg.selectOption('[data-client]',{label:/Gráfica Teste/.test('Gráfica Teste')?(await pg.locator('[data-client] option',{hasText:'Gráfica Teste'}).first().innerText()):''});
await pg.selectOption('[data-f=material]',{index:2});await pg.fill('[data-f=w]','200');await pg.fill('[data-f=h]','100');
await pg.setInputFiles('[data-upload]',['/tmp/art/old.cdr']);await pg.waitForTimeout(4000);console.log('UP:',await pg.locator('[data-upfiles]').first().innerText());await pg.waitForSelector('.upfile.is-done',{timeout:10000});
ok(await pg.locator('.upthumb').count()===1,'miniatura do CDR antigo (RIFF) no pedido manual');
await pg.fill('[data-coupon]','FIXO20');await pg.waitForTimeout(700);
console.log('resumo:',(await pg.locator('.order-sum').innerText()).replace(/\n/g,' | ').slice(0,260));
await pg.check('input[name=pagamento][value=sinal]',{force:true});await pg.fill('[name=sinal]','50');
for(const bx of await pg.locator('form input[type=checkbox][required]').all()) await bx.check();
await Promise.all([pg.waitForNavigation({timeout:20000}),pg.click('form button[type=submit]')]);
console.log('url',pg.url());console.log((await pg.locator('.flash').first().innerText().catch(()=>'')));
const id=pg.url().match(/(\d+)\/?$/)[1];
ok(/"thumb":"data:image/.test(q("echo ap_get('projects',"+id+")->items;")),'thumb gravada nos itens do pedido');
console.log('tx:',q("foreach(\\$wpdb->get_results('SELECT amount,status,method FROM '.ap_table('transactions').' WHERE project_id="+id+"') as \\$r) echo json_encode(\\$r).' ';"));
ok(/upthumb/.test(await pg.content()),'ficha do pedido mostra a miniatura');
await pg.goto(B+'/painel/projetos/');ok((await pg.locator('.kcard[data-id="'+id+'"] .kcard-thumb').count())===1,'kanban mostra miniatura do CDR');
console.log('erros JS:',errs.join('|')||'nenhum','FALHAS',F);await b.close();})().catch(e=>{console.log('EXC',e.message.slice(0,300));process.exit(1)});
