const {chromium}=require('/opt/node22/lib/node_modules/playwright');
const B='http://localhost:8082';let F=0;const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)F++;};
const fs=require('fs');const q=(c)=>{fs.writeFileSync('/tmp/qq.php','<?php require "/tmp/wpt2/wp-load.php"; global $wpdb; '+c);return require('child_process').execSync('php /tmp/qq.php').toString().trim();};
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});const pg=await (await b.newContext({viewport:{width:1300,height:1000}})).newPage();const errs=[];pg.on('pageerror',e=>errs.push(e.message));pg.on('dialog',d=>d.accept());
await pg.goto(B+'/entrar/');await pg.fill('input[name=email]','admin');await pg.fill('input[name=senha]','SENHA_DO_ADMIN_DE_TESTE');await Promise.all([pg.waitForNavigation(),pg.click('button[type=submit]')]);
ok(await pg.locator('a[href*="/painel/veiculos"]').count()>0,'menu tem Veículos');
await pg.goto(B+'/painel/veiculos/');
await pg.click('button:has-text("Cadastrar veículo")');
await pg.fill('#vei-0 [name=name]','Fiorino');await pg.fill('#vei-0 [name=plate]','abc1d23');await pg.fill('#vei-0 [name=model]','Fiat Fiorino');await pg.fill('#vei-0 [name=year]','2019');await pg.fill('#vei-0 [name=odometer]','50000');
await Promise.all([pg.waitForNavigation(),pg.click('#vei-0 button[type=submit]')]);
ok(/veiculos/.test(pg.url()),'veículo cadastrado');
const lanc=async(type,vals,paid=true)=>{await pg.click('button:has-text("Lançar custo") >> nth=0');await pg.selectOption('#vei-custo [name=vtype]',type);for(const [k,v] of Object.entries(vals)) await pg.fill('#vei-custo [name='+k+']',v);const c=pg.locator('#vei-custo [name=paid]');if(paid)await c.check();else await c.uncheck();await Promise.all([pg.waitForNavigation(),pg.click('#vei-custo button[type=submit]')]);};
await lanc('Combustível',{amount:'200,00',liters:'35,0',odometer:'50400'});
await lanc('Combustível',{amount:'210,00',liters:'30,0',odometer:'50800'});
await lanc('IPVA',{amount:'1500,00',parcelas:'3'},true);
await lanc('Seguro',{amount:'2400,00',parcelas:'4'},false);
await lanc('Multa',{amount:'130,16'});
console.log('tx:',q("echo $wpdb->get_var('SELECT COUNT(*) FROM '.ap_table('transactions').' WHERE vehicle_id>0');"));
ok(q("echo $wpdb->get_var('SELECT COUNT(*) FROM '.ap_table('transactions').' WHERE vehicle_id>0');")==='11','11 lançamentos (2+3+4+1 + ...)');
ok(Math.abs(+q("echo $wpdb->get_var('SELECT SUM(amount) FROM '.ap_table('transactions').' WHERE vehicle_id>0 AND vtype=\\'IPVA\\'');")-1500)<0.01,'IPVA parcelado soma 1500');
ok(q("echo $wpdb->get_var('SELECT COUNT(*) FROM '.ap_table('transactions').' WHERE vehicle_id>0 AND vtype=\\'IPVA\\' AND status=\\'pendente\\'');")==='2','IPVA: 2 parcelas a pagar');
const vid=q("echo $wpdb->get_var('SELECT id FROM '.ap_table('vehicles').' LIMIT 1');");const st=JSON.parse(q("echo json_encode(ap_vehicle_stats("+vid+"));"));
console.log('stats',JSON.stringify(st));
ok(Math.abs(st.kml-13.3)<0.2,'consumo km/l ≈ 13,3 (400km / 30L)');
ok(st.open>2000,'a pagar inclui parcelas em aberto');
await pg.goto(B+'/painel/veiculos/');
const txt=await pg.locator('body').innerText();ok(/Fiorino/.test(txt)&&/km\/l/.test(txt)&&/IPVA/.test(txt),'página mostra veículo, consumo e custos');
await pg.screenshot({path:'/tmp/art/veic.png',fullPage:true});
await pg.goto(B+'/painel/financeiro/?tipo=out');ok(/Veículos/.test(await pg.locator('body').innerText()),'aparece no financeiro (categoria Veículos)');
console.log('erros JS:',errs.join('|')||'nenhum','FALHAS',F);await b.close();})().catch(e=>{console.log('EXC',e.message.slice(0,300));process.exit(1)});
